//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PlaySchoolEntities : DbContext
    {
        public PlaySchoolEntities()
            : base("name=PlaySchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [DbFunction("PlaySchoolEntities", "GetMothName")]
        public virtual IQueryable<GetMothName_Result> GetMothName(Nullable<int> monthNum)
        {
            var monthNumParameter = monthNum.HasValue ?
                new ObjectParameter("MonthNum", monthNum) :
                new ObjectParameter("MonthNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetMothName_Result>("[PlaySchoolEntities].[GetMothName](@MonthNum)", monthNumParameter);
        }
    
        public virtual ObjectResult<usp_UserDetailsGet_Result> usp_UserDetailsGet(string uname, string pwd)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_UserDetailsGet_Result>("usp_UserDetailsGet", unameParameter, pwdParameter);
        }
    }
}
